### ISSUE TITLE
unsafe header

### ISSUE THREAD

**Issue by illud** [nauzethc/howlongtobeat-api#1]
Hello, for some reason it dosn't work when using with reactjs.
Any fix?.

![image](https://user-images.githubusercontent.com/61476419/184941473-d962df92-d9e0-4748-93f7-0b6d0754ce71.png)

**Comment by nauzethc** [comment]
The problem is howlongtobeat.com doesn't send CORS header on HTTP responses, because it's not an API endpoint. The purpose of this API is to use it on your Node.js backend, not in your React.js frontend. You can see an example on my playtime-react repository with React and Next.js https://github.com/nauzethc/playtime-react

**Comment by illud** [comment]
@nauzethc Thanks ;P
